### PR TITLE
Match module paths

### PR DESCRIPTION
**Pull request by TrySound**
I tried to upgrade this module in my project and stuck with not
transpiled code. After a few hours I got that before testing full
paths, webpack can test module path first. And it worked.

Can't run tests locally so rely on CI.

### CODE REVIEW

**Comment by martpie** [comment]
Hello! 

This is most probably not how it should be fixed, I am lacking some context here.

Can you open an issue to explain your issue and your setup more in details?

**Comment by martpie** [comment]
Btw, using 2.3.1 should still work for you until we figure out your problem :)

**Comment by TrySound** [comment]
Yes, it works.

**Comment by martpie** [comment]
Gonna checkout from this branch, it is actually solving the problem but it incomplete regarding hot reloading

**Comment by TrySound** [comment]
I'm not familiar with hot reloading problem. How it connected?

**Comment by martpie** [comment]
I need to add the opposite regex to the `generateExclude` function, as this how we tweak Next.js webpack configuration to support hot reloading on transpiled modules.

**Pull request merged**
