### PR TITLE
Fix #192: Reference Error: module is not defined

### LINKED ISSUE #192: Reference Error: module is not defined
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
unist-util-visit

**Describe the bug**
Described here: https://forum.rescript-lang.org/t/purpose-alternatives-to-next-transpile-modules-in-next-rescript-projects/827/12; i was having that same problem (the issue subject) and found **ryyppy** solution; i tried and it works on my code.

**To Reproduce**
nextjs project using the package i've mentioned, using this:

```javascript
const withTM = require('next-transpile-modules')(['unist-util-visit']);

module.exports = withTM({
  future: {
    webpack5: true,
  }
}
```

**Expected behavior**
My code to just work (TM)

**Setup**

- Next.js version: v15.14.0
- `next-transpile-modules` version: 6.4.0
- Node.js version:
- `npm`/`yarn` version: yarn 1.22.10
- Operating System: macOS
- Webpack 4 or 5: 5

**Additional context**
After applying **ryyppy** my code works!

### PR DESCRIPTION
**Pull request by jacargentina**

### CODE REVIEW

**Comment by martpie** [comment]
You have a formatting issue, can you fix it so we can see if the integration tests pass?

**Comment by cpouldev** [comment]
Thank you @jacargentina ! (and thank you @martpie for maintaining this fork btw). This issue was holding me back from going to webpack5. Now it works as expected

**Comment by martpie** [comment]
I would like to understand a bit better why it fixes it, I'll have to check Webpack docs. Then I'll merge it and trigger a release.

**Comment by martpie** [comment]
I'm a bit confused on what exactly goes wrong and it fixes it, but the tests are passing, so I'd say let's go. If I receive complaints due to this, I may have to go a bit deeper.

**Comment by martpie** [comment]
Released in `6.4.1`, thank you very much!

**Pull request merged**
