### PR TITLE
fix: allow transpiling of explicit nested node_modules

### PR DESCRIPTION
**Pull request by BRKalow**
Based on [the docs](https://github.com/martpie/next-transpile-modules#scoped-packages), I would expect to be able to specify explicit nested dependencies and have them be transpiled. This doesn't seem to be the case, as any potential files that are nested more than one level deep are ignored based on this logic:
https://github.com/martpie/next-transpile-modules/blob/e7222640dd72c0b4702ba5abbe79e261182a454e/src/next-transpile-modules.js#L61-L65

I've updated the default matcher to explicitly check the depth of file passed into the matcher against the depths of the modules passed into `next-transpile-modules`. This should preserve the current behavior while also ensuring explicitly listed nested packages are transpiled.

I know there have been a few discussions and PRs around this (#151, #163, and #188 to name a few), but I believe this change would make it the most predictable for users.

Alternatively, we could provide our own `__unstable_matcher`, but I'm not sure what your plans are with that API. 😄

### CODE REVIEW

**Comment by martpie** [comment]
Thank you very much for this! I'll look deeper into this soon!

**Comment by Js-Brecht** [comment]
This looks like a great solution to my own problem.  I use `pnpm`, and when resolving symlinks the modules will _always_ be nested under two `node_modules`:
```
next-transpile-modules - the following paths will get transpiled:
  - <truncated>/node_modules/.pnpm/serialize-error@8.0.1/node_modules/serialize-error
```

The second `node_modules` is essentially that module's private `node_modules`, which will contain all of its own dependencies.

This path is not something that we can guess because it depends entirely on how pnpm sets up the resolution path (e.g. `serialize-error@8.0.1` can be any number of paths, to include different version numbers, a unique hash, or dependency pairing depending on conflicts within the dependency tree).  However, none of these paths will be nested further than 2 levels, so it would even be cool to configure the desired nesting level... but the solution here is much more solid.

**Review by martpie — COMMENTED** [review]
So, if it solves it for your usecase it's great. That's indeed a mistake from myself.

That said, I feel like the code could be simplified, as even if I understand what the code does, it's not extremely straightforward to follow. I'll dive deeper in this code change and see if there is a simpler way to make it work.

**Comment by martpie** [comment]
FYI, I am trying to see if there is a way to achieve that with blobs

**Comment by martpie** [comment]
As it looks like it's working and it solves a lot of people's issues, let's merge it, and I will add a flag there is a potential to refactor/simplify this part of the code.

**Comment by BRKalow** [comment]
Thanks @martpie ! This enables us to upgrade to our apps to webpack 5. 🙏

Let me know if there's anything else I can help with, thanks for maintaining this important library!

**Pull request merged**
