### PR TITLE
[WIP] Symlink resolution / Automatic Webpack 5 optimization

### PR DESCRIPTION
**Pull request by martpie**
A potential first step to make `managedPaths` work fine in Webpack 5?

- Yarn workspaces ✅
- npm ⚠
- pnpm ✅
- berry ?

### CODE REVIEW

**Comment by paales** [comment]
@martpie What are your findings? Did you manage to get stuff to work?

**Comment by martpie** [comment]
I still have to investigate things on `npm`. On yarn workspaces and pnpm, everything seems to work fine.

Webpack 5 on Next.js will probably land soon, so the plan (for now) is the following:

1. get this working
  - check it fixes stuff for Webpack 5 users and cache is optimized
  - release it under a `beta` (v7)
2. get rid of Webpack 4 support
3. release v7 when W5 land on Next.js

**Comment by martpie** [comment]
```
~/dev/next-transpile-modules(symlink-resolution) » node --trace-uncaught src/__tests__/setup.js && npm run dev --prefix src/__tests__/__apps__/npm-basic

> test-npm-basic@1.0.0 dev /Users/pierre/dev/next-transpile-modules/src/__tests__/__apps__/npm-basic
> next

next-transpile-modules - the following paths will get transpiled:
  - /Users/pierre/dev/next-transpile-modules/src/__tests__/__apps__/_shared
  - /Users/pierre/dev/next-transpile-modules/src/__tests__/__apps__/_shared-ts
  - /Users/pierre/dev/next-transpile-modules/src/__tests__/__apps__/_shared-ui
  - /Users/pierre/dev/next-transpile-modules/src/__tests__/__apps__/npm-basic/node_modules/lodash-es
ready - started server on http://localhost:3000
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /test-scss-module
wait  - compiling...
next-transpile-modules - transpiled: /Users/pierre/dev/next-transpile-modules/src/__tests__/__apps__/_shared-ui/components/Input.jsx
next-transpile-modules - transpiled: /Users/pierre/dev/next-transpile-modules/src/__tests__/__apps__/_shared-ui/components/Input.jsx
next-transpile-modules - transpiled: /Users/pierre/dev/next-transpile-modules/src/__tests__/__apps__/_shared-ui/components/Input.jsx
next-transpile-modules - transpiled: /Users/pierre/dev/next-transpile-modules/src/__tests__/__apps__/_shared-ui/components/Input.jsx
next-transpile-modules - transpiled: /Users/pierre/dev/next-transpile-modules/src/__tests__/__apps__/_shared-ui/components/Input.module.scss
error - ../_shared-ui/components/Input.jsx
Module not found: Can't resolve 'react/jsx-dev-runtime' in '/Users/pierre/dev/next-transpile-modules/src/__tests__/__apps__/_shared-ui/components'
```

**Comment by paales** [comment]
@martpie How are those symlinks created? If someone is using npm link to symlink packages it will contain the other packages? Or is this supposed to handle [npm workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces) as well?

**Comment by martpie** [comment]
I'm talking about `npm add ../../my/package/somewhere`. for example. The symlinks are created by the package managers depending on their will. 

`yarn add` will not create symlinks. Yarn workspaces will. `npm add` will, `npm link` too (not sure), etc

**Comment by martpie** [comment]
Now the problem, is if you don't use workspaces, your dependencies are not hoisted at the root of your workspaces. So common dependencies are not reachable from "consumed" local packages.

**Comment by paales** [comment]
Might it be an intermediate to fix this for the workspaces usecase and if there is a local path, opt out of the optimizations? And suggest people to move to a workspace setup when they want both the performance and the flexibility?

**Comment by martpie** [comment]
I thought about this as well, recommending a set of "best-practices" and "official supported setups". What I am missing right now is the data to know "how many people use it for A or B or C"

**Comment by paales** [comment]
@martpie Did you find any time to take a deeper look at this?

**Comment by andrekorolev** [comment]
Hello @martpie!
Thanks for your contribution in Next.js project. 
Did you have any chance to dig deeper in problem about NPM symlinks?

**Comment by martpie** [comment]
Hello there, no, not much. Having a solution from Webpack would still be my preferred solution, because i this change could theoretically work, each package manager works a little bit differently, and I would like to not introduce any "package manager specific" code in the project.

We have two scenarios now:

- we wait for Webpack to provide a `nonManagedPaths` option
- we deprecate the usage for package managers without workspaces support (npm with `file://` for example)

The second point is the easy path (this PR is ready, technically), but I have no idea it will break any current setup. I don't have any numbers, but if it's 2% of the users of `ntm`, then I'm fine with that. If it's 50%, then it's something else.

**Comment by paales** [comment]
> we wait for Webpack to provide a nonManagedPaths option

@martpie Extending/modifying webpack is a whole other beast. I unfortunately don't have the in depth knowledge / time to invest on the PR. I've closed the PR in the webpack repo.

**Comment by andrekorolev** [comment]
I've just tried to migrate to Yarn Workspaces, but now I see new error in console
`Error: next-transpile-modules - an unexpected error happened when trying to resolve "@org/bar"`
This happens after upgrade to next@10.0.6 and next-transpile-modules@6.2.0

I see, that Yarn creates symlinks on root level and it looks like:
@org/package -> ../../packages/bar

In example that you provided https://github.com/vercel/next.js/tree/canary/examples/with-yarn-workspaces/ the structure of modules is absolutely the same. What can be the issue here?

**Comment by martpie** [comment]
I'm at the point where I am hesitating to add a message after installing `next-transpile-modules` to ask people to answer a small form with what their setup is. But I would hate to do it.

Another thing I could do is ask someone at Vercel (Tim maybe?) to retweet a Twitter survey that I would do, as I don't have a large audience there.

**Comment by paales** [comment]
@martpie Any updates on this? 😇

**Comment by martpie** [comment]
I just re-poked @timneutkens on Slack regarding the survey. But otherwise, no move from the Webpack team (I did not poke them though)

**Comment by martpie** [comment]
see #179

**Pull request closed without merging**
