### PR TITLE
Adds path.normalize to modulName check

### PR DESCRIPTION
**Pull request by lukeundtrug**
Moves webpackMatcher outside of withTmInitializer for unit testing
Adds rudimentary unit tests for webpack matcher

Hi there @martpie,

a colleague and me found an issue in the v6.1.0. Specifically, the module names that we supplied didn't get transpiled anymore. This was due to a change in v6.1.0 which, as it seems, broke support for transpiling scoped modules on Windows systems.

We took the liberty to try and fix it ourselves and this is the resulting PR. The fix itself is very trivial. We wrapped the module-names supplied to the webpack matcher function in a path.normalize. I also tried to add some unit tests to the matcher function but haven't managed to get the tests to run locally. That is maybe something I could still use some help with.

Another thing that's still sub-optimal is the way that the logger needs to be supplied to the matcher function as an argument, there might be a better way to solve this.

Let me know if I can help in any other way or if the PR doesn't meet certain standards :)

### CODE REVIEW

**Comment by lukeundtrug** [comment]
The last problem at the moment is the unit tests which check for what should actually be a non-issue. I included some tests for using Windows style path separators on Unix style paths. Nobody should actually do that. Nevertheless, it would be nice to check the possibility 🤔

**Comment by lukeundtrug** [comment]
Tests are green now and thew two specs that are commented out at the moment probably are not fixable because they are inherently OS-dependant. Maybe it would be better to just delete them again.

**Review by martpie — COMMENTED** [review]
Thank you very much, I indeed forgot the windows case for nested modules. Regarding jest tests, do you think we could run the windows tests conditionally with mocks?

Something like https://stackoverflow.com/questions/58264344/conditionally-run-tests-in-jest

**Comment by martpie** [comment]
Sorry, I screwed my conflict merging, I'll try to fix it later.

**Comment by martpie** [comment]
Released in `6.2.0`, thank you!

**Comment by lukeundtrug** [comment]
Sorry for not replying earlier, was a bit caught up for the last two days. Thank you for finishing it and for providing such a great module :)

**Pull request merged**
