### PR TITLE
feat: Support Webpack 5

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
Resolves: #72

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
Any assistance on tests? not 100% sure how they are set, this seems to resolve W5 issues though. Can discuss it happily

**Comment by martpie** [comment]
Well this is interesting, because I see some similarities with #89 

@ScriptedAlchemy do you know if Webpack 5 is going to be use in the next Next.js release (and if it will be soon or in months?)

**Comment by ScriptedAlchemy** [comment]
Currently running it in production. If you yarn resolution W5, next has full compatibility as of 9.4.5-canary. There's a single outstanding PR for serverless environments which i already opened a PR against :)

**Comment by ScriptedAlchemy** [comment]
A large effort was put forth to keep W4 and W5 functionality working with next. I've applied the same tactics in my pr as used in the PRs opened and merged into next. The only area I cannot mend easily is your tests (I'm bad with tests and have an enormous list of community plugins to upgrade) hopefully this helps and can assist on any webpack code as required

**Comment by martpie** [comment]
Thanks, I think I can tackle it from here! 🙌

> I have an enormous list of community plugins to upgrade

Out of curiosity, how is this happening?  Is Webpack investing resources to update the compatibility of famous plugins/loader before the release? I would have thought it was up to maintainers to keep their stuff up to date

**Comment by ScriptedAlchemy** [comment]
Appreciate it! 

Sheer willpower, I created Module Federation and want to use it at my own company. Our architecture was designed around it (started about a year ago, before id actually made MF). It's pretty much just me upgrading anything that stands in my way of a successful build 📦 that can leverage module federation, unlocking the full potential of the platform i designed haha. Nex.js was the main blocker, with that resolved I've moved on to address any and all other third-parties in my dependency chain.

**Comment by ScriptedAlchemy** [comment]
@martpie adding support for non-webpack 5 versions of next 9.4.5

**Pull request merged**
