### PR TITLE
Add babel match parameter

### PR DESCRIPTION
**Pull request by RenaudRohlinger**
In some specific cases, we need to be able to override the babel include condition.
This PR simply adds a match parameter.

For example : 
```jsx
const match = (path) => {
  return path.includes('three/examples/jsm')
}

const withTM = require('next-transpile-modules')(
  ['three', '@react-three/drei', '@react-three/postprocessing'],
  { unstable_webpack5: true, match }
)
```

### CODE REVIEW

**Comment by martpie** [comment]
Can you elaborate on your usecase?

**Comment by martpie** [comment]
Can you elaborate on your usecase?

**Comment by RenaudRohlinger** [comment]
Basically without this simple condition "path.includes('three/examples/jsm')" the module was transpiling three.module.js over and over again, causing babel compact parameter to do compression (we can see the 4 seconds gap in that screenshot) while in my case we don't need 80% of the files that are getting transpiled.
Screen Shot 2021-01-13 at 21 13 23

Some before/after tests I did using webpack5 :
Screen Shot 2021-01-13 at 20 55 32

I just want to transpile what is really necessary and not the whole library. It has been tested and works perfectly in dev and build with webpack4 and 5.

**Comment by JackCA** [comment]
Stumbled upon this and have the same exact issue (next.js + three.js)

**Comment by martpie** [comment]
Can you elaborate more on your usecase/problem?

My reticence does not come directly from this feature, but more from the implications it has on all the scope of this plugin (CSS support, etc). I'd like to understand a bit more the problem before merging this (or work on an alternative)

**Comment by JackCA** [comment]
@martpie I understand wanting to limit the scope of the project for sure.

For this example, three.js transpiles it's core build already, but it also has non-core features that are included in an example directory which is (like @RenaudRohlinger is showing).

It's very edge-casey, and I personally haven't run into other libraries with this issue.

**Comment by martpie** [comment]
@RenaudRohlinger there were quite some changes in the last days for fixes/new features, could you maybe update your branch with `master`?

And if possible add unit tests 🙌 Otherwise, it looks ok to me, but I would limit that that to JS/TS files only, and exclude anything else (fonts, CSS, etc...).

**Comment by RenaudRohlinger** [comment]
@JackCA @martpie if you have the time it's literally just changing these two lines :
`include: matcher`
https://github.com/martpie/next-transpile-modules/blob/master/src/next-transpile-modules.js#L214
https://github.com/martpie/next-transpile-modules/blob/master/src/next-transpile-modules.js#L226

by : `include: options.match || matcher`.

I have no idea how the test works and I don't want to break anything.

Otherwise, I will check that this weekend

**Comment by martpie** [comment]
The matcher condition became a little bit more complex recently, so I wonder if this new parameter should supercharge or replace it.

Probably the former.

**Comment by RenaudRohlinger** [comment]
@martpie If someone replaces the matcher condition he is totally aware of what he's doing. We could add a "danger" in the readme next to the option. Also, we might want to do so additional stuff. For example, I added a timer on my matcher function to check the build time.
If not, it's easy to simply copy the createWebpackMatcher function since this one doesn't depend on anything.

**Comment by martpie** [comment]
That sounds good to me to add this parameter behind a flag 👍

I'll try to do that this afternoon

**Comment by martpie** [comment]
I added a `__unstable_matcher` parameter on `master`. Now it's super experimental, and definitely the wrong way to do it.

Having a middleware system with `next()`s would imho by something more robust. I'll give it a thought and see how easy it would be to implement.

**Comment by martpie** [comment]
@JackCA @RenaudRohlinger ☝️ 

- What do you think? Is this enough for your usecase? 
- Is it fine if I introduce a middleware system instead/in a future release (will break between minor versions, you might want to fix the package version, or use `~` instead of `^`)

**Comment by RenaudRohlinger** [comment]
@JackCA @martpie it's perfect for my case thank you very much. For example, I use the new parameter here: 
https://github.com/pmndrs/react-three-next/blob/main/next.config.js

You're right, a middleware would be indeed better for maintenance.

**Comment by JackCA** [comment]
Agreed on all points, thanks @martpie for adding this but I support a better longterm solution

**Comment by martpie** [comment]
This is now available in 6.3.0. I highly recommend you fix this version because I might change this parameter in a minor release (to go with a middleware system or something)

**Pull request closed without merging**
