### PR TITLE
feat: get HMR running in next 10

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
I had to update the resolution function. It does not appear to resolve my workspace packages. 

Heres what `require.main.paths` is
```
[
  '/Volumes/lulu_dev/ecom-web-app/packages/ecom-site/server/node_modules',
  '/Volumes/lulu_dev/ecom-web-app/packages/ecom-site/node_modules',
  '/Volumes/lulu_dev/ecom-web-app/packages/node_modules',
  '/Volumes/lulu_dev/ecom-web-app/node_modules',
  '/Volumes/lulu_dev/node_modules',
  '/Volumes/node_modules',
  '/node_modules'
]
```

if i try resolve.sync and use basedir, looping over each possible node_modules resolution path - it doesn't find anything. 

the originals sit in `ecom-web-app/packages`

The only thing left is to properly resolve managed paths to their packages, path.dirname seems to trim company workspace packages and makes the path too broad. 

This does hot reload though.

### CODE REVIEW

**Review by martpie — APPROVED** [review]
Awesome thanks! I will probably try to clean things up a little bit and indicate that we want to move away from regexes, but if it works, then 99% of the work is done 🙌

**Comment by martpie** [comment]
@ScriptedAlchemy I think you have a problem in your setup, you might not be using Webpack 5: 

```
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].watchOptions.ignored should be one of these:
   [non-empty string, ...] | non-empty string
   -> Ignore some files from watching (glob pattern).
   Details:
    * configuration[0].watchOptions.ignored should be an array:
      [non-empty string, ...]
    * configuration[0].watchOptions.ignored should be a non-empty string.
      -> A single glob pattern for files that should be ignored from watching.
 - configuration[1].watchOptions.ignored should be one of these:
   [non-empty string, ...] | non-empty string
   -> Ignore some files from watching (glob pattern).
   Details:
    * configuration[1].watchOptions.ignored should be an array:
      [non-empty string, ...]
    * configuration[1].watchOptions.ignored should be a non-empty string.
```

**Comment by martpie** [comment]
What version of Webpack did you test?

**Comment by martpie** [comment]
Ok, I managed to resolve the Webpack error, but HMR is not working ><

**Comment by ScriptedAlchemy** [comment]
were you able to resolve the hmr issue? i was on webpack ~5.4

**Comment by martpie** [comment]
I managed to get passed the Webpack errors, but saving a file does not do anything (cf. Webpack 5 example in the repo)

**Comment by ScriptedAlchemy** [comment]
I'll try your repo. I'm kinda back-porting my fork which is built to solve my exact repo issues to unblock a big rollout. I'll need to try this on smaller repos. 

I think my latest PR might smooth it all out. It's much better then anything else I tried so far with HMR and cache management.

**Pull request merged**
