### PR TITLE
Preserve webpack's default behaviour of resolving symlinks

### LINKED ISSUE #36: ModuleNotFoundError using pnpm
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Describe the bug**
Using [pnpm](https://github.com/pnpm/pnpm)@3.4.1, this error is produced when using next-transpile-modules:

```
[ ModuleNotFoundError: Module not found: Error: Can't resolve 'object-assign' in '/Users/spencerelliott/Dev/path/to/repo/packages/login-web/node_modules/react-dom/cjs'
    at factory.create (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/webpack/4.29.0_webpack@4.29.0/node_modules/webpack/lib/Compilation.js:823:10)
    at factory (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/webpack/4.29.0_webpack@4.29.0/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/webpack/4.29.0_webpack@4.29.0/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/webpack/4.29.0_webpack@4.29.0/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/neo-async/2.6.1/node_modules/neo-async/async.js:2830:7
    at /Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/neo-async/2.6.1/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/webpack/4.29.0_webpack@4.29.0/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/tapable/1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/tapable/1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/tapable/1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve 'object-assign' in '/Users/spencerelliott/Dev/path/to/repo/packages/login-web/node_modules/react-dom/cjs'
  Parsed request is a module
  using description file: /Users/spencerelliott/Dev/path/to/repo/packages/login-web/node_modules/react-dom/package.json (relative path: ./cjs)
    resolve as module
      /Users/spencerelliott/Dev/path/to/repo/packages/login-web/node_modules/react-dom/cjs/node_modules doesn't exist or is not a directory
      /Users/spencerelliott/Dev/path/to/repo/packages/login-web/node_modules/node_modules doesn't exist or is not a directory
      /Users/spencerelliott/Dev/path/to/repo/packages/node_modules doesn't exist or is not a directory
      /Users/spencerelliott/Dev/path/to/repo/node_modules doesn't exist or is not a directory
      /Users/spencerelliott/Dev/Yolk-HQ/node_modules doesn't exist or is not a directory
      /Users/spencerelliott/Dev/node_modules doesn't exist or is not a directory
      /Users/spencerelliott/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
```

This happens due to the fact that pnpm relies on symbolic links inside of `node_modules`, and next-transpile-modules disables webpack's resolution of symlinks:

https://github.com/martpie/next-transpile-modules/blob/0e76c25528d961ad1843ccdddf3de0e77e9ff9aa/index.js#L46

**To Reproduce**
Set up a new project using pnpm@3.4.1, next@8.0.4, and next-transpile-modules@2.3.1. Run `next dev` and observe the error above.

Minimal reproduction: https://github.com/elliottsj/next-transpile-modules-issue-36

**Expected behavior**
The above error does not occur, and the application starts normally.

**Setup**

- Next.js version: 8.0.4
- `next-transpile-modules` version: 2.3.1
- Node.js version: 10.15.0
- `npm` version: N/A
- Operating System: macOS

### PR DESCRIPTION
**Pull request by elliottsj**
Fixes #36

### CODE REVIEW

**Comment by martpie** [comment]
The symlinks option is necessary to avoid webpack resolving imports with files realpath instead of the symlinked one in `node_modules`.

We should come up with another solution.

**Comment by elliottsj** [comment]
I'm curious of the reason why it's necessary to avoid resolving symlinked files to their real path? In my project, I haven't had any issues when using next-transpile-modules and setting `config.resolve.symlinks = true;`.

**Comment by martpie** [comment]
so the thing is if you use npm to install a local module (e.g `npm install ../styleguide`), the module will be install in `node_modules` as a symlink. 

When Webpack will require the `styleguide` files to bundle them, `config.resolve.symlinks = true` would resolve them with their relative path `../styleguide/components/Button` (for example), instead of `node_modules/styleguide/components/Button.tsx`.

Then transpilation and hot reloading do not work (obviously). 

So we need to support various scenarios (npm modules, local modules with npm install, yarn workspaces, and now pnp), I am sure we can find a way to fix this correctly, but this change is not the correct one :)

**Comment by martpie** [comment]
I have an idea to make things work for all scenarios, but it would require dropping support for Regex (which I think is fine). I need to spend some time experimenting. In the meantime, I guess you can use your fork :)

**Comment by elliottsj** [comment]
Makes sense; thanks for the explanation 😄

**Comment by rohmanhm** [comment]
`config.resolve.symlinks = true;` solving my problem here.
Before I change the symlinks to `true` I have to restart my nextjs project over and over again.
But when I changed it to `true` I don't have to do restart anymore. The hot reloading is working.

Thanks.

**Comment by martpie** [comment]
What do you use @rohmanhm ? npm local install, yarn workspaces, pnpm?

**Comment by rohmanhm** [comment]
I'm trying to transpile local modules.
And I'm using yarn.

Setting up yarn workspaces doesn't work.

**Pull request closed without merging**
