### PR TITLE
Support `module` field in package.json

### LINKED ISSUE #156: Support `module` field in `package.json`
**Is your feature request related to a problem? Please describe.**

`next-transpile-modules` only allows `enhanced-resolve` to look at the `main` and `source` fields in a package's `package.json`. Since `next-transpile-modules` is made to be used with `next.js` and `next.js` uses `webpack` for building and since `webpack` [supports the `module` field](https://webpack.js.org/guides/author-libraries/#final-steps), `next-transpile-modules` should do so, too.

The `module` field is used in ES modules instead of the `main` field.

**Describe the solution you'd like**

Add the `"module"` field to the [list of `mainFields`](https://github.com/martpie/next-transpile-modules/blob/9f9371e6570614bef25ee603d248ab5a4ec2b9e7/src/next-transpile-modules.js#L22).

**Describe alternatives you've considered**

I don't think there is another way to reach this goal.

**Additional context**

I noticed this issue when trying to transpile [`indefinite-observable`](https://www.npmjs.com/package/indefinite-observable), which in turn is used by [`@material-ui/core`](https://www.npmjs.com/package/@material-ui/core), which is an at least somewhat popular UI framework. Supporting it would be nice.

### PR DESCRIPTION
**Pull request by yeldiRium**
This closes #156.

### CODE REVIEW

**Comment by martpie** [comment]
Do you have any documentation I could read about this convention?

**Comment by yeldiRium** [comment]
Hi :wave:,

thanks for the quick response. I only have what I already linked in the issue and [this proposal/documentation from rollup](https://github.com/rollup/rollup/wiki/pkg.module).

**Comment by martpie** [comment]
Thank you very much for the link, looking good to me then 👍 

I'm still a little bit confused about one thing: Webpack would still be in charge of deciding which bundle to get, right? This is really just for packages who only exposes `module` and not `main`?

**Comment by yeldiRium** [comment]
Yes, that's how I understand it as well.

**Comment by martpie** [comment]
Will trigger a release once #152 is merged.

**Comment by yeldiRium** [comment]
Thanks a lot for taking the time :)

**Comment by thesiti92** [comment]
When will this get released? these fixes are HUGE for monorepos :)

**Comment by thesiti92** [comment]
epic ty man

**Comment by martpie** [comment]
You can always use GitHub URLs in your `package.json` https://docs.npmjs.com/cli/v6/configuring-npm/package-json#github-urls

It should be available in `6.1.0` :)

**Comment by thesiti92** [comment]
yes, i was using those to test locally. just hard to get someone else to approve my code when the package json has some sketchy commit hash 😅

**Comment by martpie** [comment]
it's published now :)

**Comment by martpie** [comment]
ok it's there!

**Pull request merged**
